// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlxlPcaQKCjFvrvGT8-RkXhxblcYuyWfM',
    appId: '1:845838373805:web:680112fc0d310e6e150724',
    messagingSenderId: '845838373805',
    projectId: 'emergencyone-af60c',
    authDomain: 'emergencyone-af60c.firebaseapp.com',
    storageBucket: 'emergencyone-af60c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuvssxxwDMoR-C6FO1AWa8uBug9jC6v5g',
    appId: '1:845838373805:android:a1b95416c5a903e9150724',
    messagingSenderId: '845838373805',
    projectId: 'emergencyone-af60c',
    storageBucket: 'emergencyone-af60c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx2_MYP5qNhTvQb8zn8sqd-ohYhOwf1CY',
    appId: '1:845838373805:ios:ef0676f38068118b150724',
    messagingSenderId: '845838373805',
    projectId: 'emergencyone-af60c',
    storageBucket: 'emergencyone-af60c.firebasestorage.app',
    iosBundleId: 'com.example.emergencyone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx2_MYP5qNhTvQb8zn8sqd-ohYhOwf1CY',
    appId: '1:845838373805:ios:ef0676f38068118b150724',
    messagingSenderId: '845838373805',
    projectId: 'emergencyone-af60c',
    storageBucket: 'emergencyone-af60c.firebasestorage.app',
    iosBundleId: 'com.example.emergencyone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlxlPcaQKCjFvrvGT8-RkXhxblcYuyWfM',
    appId: '1:845838373805:web:258865c18f60de25150724',
    messagingSenderId: '845838373805',
    projectId: 'emergencyone-af60c',
    authDomain: 'emergencyone-af60c.firebaseapp.com',
    storageBucket: 'emergencyone-af60c.firebasestorage.app',
  );
}
